### ISSUE TITLE
working --kind of

### ISSUE THREAD

**Issue by delboydell** [ndg63276/alexa-sky-hd#10]
I have the skill working and my box was found ok.
However channel change commands dont work i get a hmm I dont know that one,
power on off is ok
tv guide is ok
info is ok
pause is ok 
play is not working 
and the positions for netflix and youtube are wrong, but the command tries to do it?

any ideas? 
thanks in advance

**Comment by delboydell** [comment]
I have very little skill in this programming, but looking in the zipped file that has been uploaded to the AWS there are 3 sets of channel listings, is this the reason channel changing is not working as 101 points to different stations ? I could be wrong?
UPDATE, I have just been into the code area and deleted the .IT json file and she still does not know that ?

**Comment by ndg63276** [comment]
1) What country are you in?
2) What type of Sky box do you have?
3) What (exactly) are you saying to Alexa when it doesn't work?

Thanks.

**Comment by delboydell** [comment]
hello, 
I am in the UK
I have a sky q box
and i say alexa change channel to bbc1 on sky box
Thanks in advance

**Comment by gavinsbtm** [comment]
Might not be the issue but BBC have many local variations. For example, if I say change channel to BBC One, it wouldn't work but if I say change channel to BBC One West Midlands - it does.

The lambda_funtion.py points to http://epgservices.sky.com/5.1.1/api/2.1/region/json/4101/1/ to get the channel list so unless you have changed the path to one of the local json files, editing them will not help.

**Comment by ndg63276** [comment]
If Alexa is saying "Hmmm, I don't know that one", it suggests she is not passing on the request to the Sky box skill.

If you say the command, get the response, don't do any other requests. Then go to https://eu-west-1.console.aws.amazon.com/cloudwatch/home?region=eu-west-1#logs:, click on your Sky box logs, and see if there are any recent logs.

If there aren't any, then Alexa is not sending the command to the right skill, so you might have to figure out a new way to word it.

What Alexa device are you using? Spot, Show etc? Try using one without a screen if possible.

And do you have a Fire Stick plugged in? Try unplugging it, so Alexa doesn't try to show it on that.
