### ISSUE TITLE
Static ip

### ISSUE THREAD

**Issue by OldManKreature** [ndg63276/alexa-sky-hd#13]
I managed to get the skill to work for a while and it was great while it lasted, so thank you for your work.

I have recently been given a static ip by my service provider and wanted to see if I could set this up again without using my.noip.com as the hostname expires every 30 days.

could you help me?

TIA

#stayhome #staysafe #protecttheNHS #savelives

**Comment by ndg63276** [comment]
You should be able to use your static IP as the HOST variable, absolutely. Just go to https://whatismyipaddress.com/ and use that IP address. Let me know how you get on.

**Comment by Jasefern** [comment]
I have used my static IP in the host and although  I have a different problem it think that prt worked

**Comment by Jasefern** [comment]
I am using my static ip as my router won't allow DDNS and I had a problem which was caused by leaving http:// in the host it now works correctly

**Comment by ndg63276** [comment]
Great!
