### ISSUE TITLE
Not working?

### ISSUE THREAD

**Issue by Jasefern** [ndg63276/alexa-sky-hd#14]
Followed best I could but some things not the same as instructions so took longer to find them .
Having completed all the steps I tried to enable skill on the App which should have asked for the authentication but instead the following error 
"The authorisation server returned with an error parameter. Please refer to https://tools.ietf.org/html/rfc6749#section-4.1.2.1 for more details."

I have scope set to user_id as per the previous issues 

Any ideas would be good as I have hit a wall

**Comment by ndg63276** [comment]
It should still be working, but you're right, some of the instructions were out of date. I've tried to update them. Unlinking and re-linking still works for me, so hopefully it is something straightforward to get it working for you,

If you go to https://developer.amazon.com/alexa/console/ask#/skills, click on your Skybox skill, and then click on Account linking on the left, check the following settings:

Allow users to link their account to your skill from within your application or website: **Disabled**
Authorization URI: **https://www.amazon.com/ap/oa**
Access Token URI: **https://api.amazon.com/auth/o2/token**
Your Authentication Scheme: **HTTP Basic**
Scope: **profile:user_id**

**Comment by Jasefern** [comment]
Thanks I will check tomorrow I think "Allow users to link their account to your skill from within your application or website: Disabled"
Is enabled

**Comment by Jasefern** [comment]
Deleted all and started again now linked and device found in Alexa app but different problem now so will close this and read issues before posting another
