### ISSUE TITLE
BBC 1 in Scotland

### ISSUE THREAD

**Issue by darkbluedad** [ndg63276/alexa-sky-hd#16]
Thanks for creating this - I have got it working and it does exactly what I wanted, namely letting me change the channel using Alexa from our deck where I have Speakers connected up to Sonos Amp which has a line in from our Sky box. The only minor issue is that asking for BBC1 gives Channel 115, which in Scotland is BBC Scotland. Our BBC1 HD is on 101. I can ask for 101 which works fine but it would be good if you could create a parameter like your Italy one.
Have also noticed that sometimes you don't need to add "on Sky" to channel commands if you have recently issued a command with "on Sky".

**Comment by darkbluedad** [comment]
Thanks for creating this - I have got it working and it does exactly what I wanted, namely letting me change the channel using Alexa from our deck where I have Speakers connected up to  Sonos Amp which has a line in from our Sky box.  The only minor issue is that asking for BBC1 gives Channel 115, which in Scotland is BBC Scotland.  Our BBC1 HD is on 101.  I can ask for 101 which works fine but it would be good if you could create a parameter like your Italy one.

**Comment by ndg63276** [comment]
Hi there, assuming you set this up in the last 10 days, there is now an environment variable that lets you do this. In your lambda function, set the environment variable with the key "CHANNELS_FILE", and the value "http://epgservices.sky.com/5.1.1/api/2.1/region/json/4102/37/". That is for the region "Scottish East HD", which seems to have BBC One as you expect it. I will try and document all the regions, as I'm sure this would be useful for others.

**Comment by darkbluedad** [comment]
Excellent!

Thank you

**Comment by darkbluedad** [comment]
Tried that - Now get BBC one HD but not on 101 but on 976.   I guess because 101 is called BBC One ScotHD on the screen.

**Comment by ndg63276** [comment]
Ok, plan B then!

If you go to Lambda, scroll down to the Function Code section, you should see a little file explorer. On the left, there's a file called "channels-hd.json". Double click to open it, you should be able to edit it. Just change the top lines to like this:

```
{
	"101": ["BBC One HD", "bbc 1 hd"],
	"102": ["BBC Two HD", "bbc 2 hd"],
	"103": ["ITV"],
	"104": ["Channel 4", "channel four"],
	"105": ["Channel 5 HD", "channel five hd"],
	"106": ["Sky One HD", "sky 1 hd"],
	"107": ["Sky Witness HD"],
	"108": ["Sky Atlantic HD"],
	"109": ["W HD"],
	"110": ["GOLD HD"],
	"111": ["Dave HD"],
	"112": ["Comedy Central HD"],
	"113": ["Universal HD"],
	"114": ["SYFY HD", "sci-fi hd"],
	"115": ["BBC Scotland HD", "bbc scotland hd"],
	"116": ["BBC Four HD", "bbc 4 hd"],
...
```
And click Save.

Then change that environment variable again, keep the key as "CHANNELS_FILE", change the value to "channels-hd.json" (ie the name of the file you edited). Click Save again and try that.

**Comment by darkbluedad** [comment]
Many thanks 

As an aside do I need to deactivate/activate the skill after the change or will it just pick up the new code?

**Comment by ndg63276** [comment]
It should just work as soon as you click save.

**Comment by darkbluedad** [comment]
Many thanks

Will test when my dear wife has finished watching the news - I'm not planning releasing this new Alexa feature to the production user audience till it works to my satisfaction - Even though I'm retired I like to keep my development standards up!

Cheers

**Comment by darkbluedad** [comment]
BBC One working fine now - Thank you -I also changed 103 to STV as that's what we call it.   To get BBC Scotland (Channel 115) to work I have to say "BBC Scotland HD" I tried removing the HD from the line in channels-hd and also adding "BBC Scotland" with a channel  number of 876 but Alexa says "Sorry I don't know that"

**Comment by darkbluedad** [comment]
Had a quick look in the code but I can't immediately work out what is going wrong - Probably too late to be debugging!

**Comment by ndg63276** [comment]
If she's saying "Sorry I don't know that", then she is not invoking the Skybox skill, that message is not in my code anywhere. Make sure to say "... on sky box", but even then Alexa can be a bit flaky as to whether to invoke my skill. If I ask for BBC Scotland, she goes off to some other skill, very annoying!

**Comment by darkbluedad** [comment]
Yesterday I had to disable/enable the sky skill to get it working - have you come across that?

**Comment by ndg63276** [comment]
No, but the skill as a whole is a bit sketchy. Alexa constantly wants to do things herself rather than invoking the skill, so it seems like it's not working, but actually it's just not being used.

**Comment by darkbluedad** [comment]
Alexa is sometimes too clever for her own good.
