### ISSUE TITLE
Alexa skill for sky q issue

### ISSUE THREAD

**Issue by gaoguitar** [ndg63276/alexa-sky-hd#17]
good evening I  have a problem with this skill, after following all the configuration I managed to find the sky q decoder, but when I ask for example to turn on or off it says there are problems. In the log I find the following error (I specify that 9006 is the port that I opened in the modem and it is correctly configured using the tool)

'9006': KeyError
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 196, in lambda_handler
    response = handle_non_discovery(request)
  File "/var/task/lambda_function.py", line 445, in handle_non_discovery
    send_command(command, endpointId)
  File "/var/task/lambda_function.py", line 491, in send_command
    port = int(environ['9006'])
  File "/usr/lib64/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: '9006'

**Comment by gaoguitar** [comment]
if i say a command alexa says : i am sorry the sky box device is not responding

**Comment by ndg63276** [comment]
So have you edited the lambda_function.py script? Because line 491 is:

    port = int(environ['PORT'])

And you seem to have changed it to:

    port = int(environ['9006'])

which is always going to fail. You are supposed to leave it as it is, and then add an environment variable with the key PORT and the value 9006.

**Comment by gaoguitar** [comment]
you are the best!!!! 
thank you very much
