### ISSUE TITLE
Python 2.7

### ISSUE THREAD

**Issue by darkbluedad** [ndg63276/alexa-sky-hd#21]
just got a mail from Amazon regarding end of support for Python 2.7 - is it just a matter of selecting the latest Python version in a drop down?

Regards

**Comment by ndg63276** [comment]
Let me look at it, there'll be a few changes.

**Comment by darkbluedad** [comment]
Thanks

**Comment by ndg63276** [comment]
Ok, I have updated the lambda function. You can either update the python file, or re-upload the zip file. And then update the Runtime to python 3.7.

**Comment by darkbluedad** [comment]
Thank you
