### ISSUE TITLE
Youtube

### ISSUE THREAD

**Issue by random-robbie** [ndg63276/alexa-sky-hd#25]
Hey,

Have you ever seen it when using sky q / Alexa for when you ask to turn on YouTube it just goes to the last on demand video you watched in my case BBC iPlayer stuff.

I'll have a review of logs shortly.

Regards,
Robbie

**Comment by ndg63276** [comment]
Unfortunately I don't have Sky Q, so I don't get to do much testing. The button presses it does to get to Youtube are:

'tvguide','right','down','down','down','down','down','right','right','select'

so if the interface has changed slightly, it might go to a different screen.

**Comment by random-robbie** [comment]
Ok what I'll do here is I'll submit a pull request once I work it out. I have to check if every one else's sky q is the same to get to it.
