### ISSUE TITLE
Working but some strange things happening.

### ISSUE THREAD

**Issue by g0sbv** [ndg63276/alexa-sky-hd#27]
Hi Mark, I am amazed at how you managed to accomplish this... being disabled makes things a little easier for me. Well I have managed to get it to work just a couple of things I cant figure out. If I want to close the Tv Guide on my sky q box as on power on it defaults to on and highlighting Home so if I say Alexa, turn off Tv Guide it jumps to recordings and highlights Most Recents. If I manualy close it and say Alexa, turn on Tv guide it opens it but if I ask it to turn off jumps to recordings and highlights Most Recents again. Turning on and off, play, pause, ffwind, rewind change channel by name or by number all works fine.
If I ask it to turn on info that works displays at the bottom of the screen with current playing programe but when I tell it to turn off info it goes to Tv Guide showing what is currently being played in the previous info picture screen. I did a test event
 I wonder if you are in a position to have a look at this for me if you are not able to or do not do this stuff anymore then I appologise for bothering you
regards Ricky
 
[Test event.txt](https://github.com/ndg63276/alexa-sky-hd/files/8017089/Test.event.txt)

**Comment by ndg63276** [comment]
Hello, I'm happy to have a look at this. The only problem is I don't have Sky Q so I can't test anything!

Turning off the TV Guide is set as if you are pressing the "Sky" button itself. That works fine on a SkyHD box, but obviously goes to recordings on SkyQ. Is there a button (or series of buttons) to press that would just close the TV guide? I'm guessing the "Dismiss" button?

In which case, you just need to change line 404 of lambda_function.py from:

```
                commands.append('sky')
```

to 

```
                commands.append('dismiss')
```

Make sure not to change the indentation.

Let me know how you get on!

**Comment by g0sbv** [comment]
Hi I replied direct to the email from github sent by you I don't know if github actualy sends it as nothing showing in conversation here, applogies if you have already have received it.
Anyway the ('dismiss') that worked great, the last issue is INFO I can call it up but not close it instead it goes to Tv Guide I tried changing line ('i') 449 but that was obviously the wrong one as it stopped me being able to call up info so reverted it back again, what should i change as it also uses the dismiss key to close it at the moment I use the command Alexa, info off then Alexa, tvguide off.
regards
Ricky

**Comment by ndg63276** [comment]
You'll need to do a couple of changes. Instead of this:
```
        elif endpointId == "skybox-info":
            if request_name == "Activate":
                name = "ActivationStarted"
            if request_name == "Deactivate":
                name = "DeactivationStarted"       
            commands.append('i')
```
You need:
```
        elif endpointId == "skybox-info":
            if request_name == "Activate":
                name = "ActivationStarted"
                commands.append('i')
            if request_name == "Deactivate":
                name = "DeactivationStarted"       
                commands.append('dismiss')
```

**Comment by g0sbv** [comment]
Hi I would like to thank you for your help with both fixes it works fine, certainly made things easier for me trying to find the correct buttons with poor eyesight it can be difficult especially as I have two different controllers in the bedroom a new style one and in the lounge and older style one which I prefer but the buttons are not in the same places.
I can see that you have put a lot of time and effort in this in the past..
The controls I can confirm that work with Sky q the latest box.

**Turn on and off
Turn on and off TV guide
Turn on and off info
Turn on youtube
Turn on spotify
Turn on netflix
Play back control
Change channel by number
Change channel by name
Up and down channels**

Once again thank you for your time its much appreciated..
regards
Ricky
