### ISSUE TITLE
epgservices returning null for some channels

### ISSUE THREAD

**Issue by henhouseharry** [ndg63276/alexa-sky-hd#29]
Within the last month EPG Services http://epgservices.sky.com/5.1.1/api/2.1/region/json/4101/1/ has been returning null for some channels e.g. 106: Sky Showcase. About 70 channels are affected.

I raised this as a question on the Sky Community but they never even approved my post.

**Comment by henhouseharry** [comment]
Sky Community flagged my post as spam, but accepted it when I pointed out it is a subdomain of sky.com and certainly one of their services. The data was fixed at some point between 3am and 10am (last time I checked it) on 2nd August 2022. Sky Go seems to use this data and the channel names e.g. 106 Sky Showcase was corrected on that day.

**Comment by ndg63276** [comment]
Hopefully no longer a problem, thanks for chasing up with Sky Community!
