### ISSUE TITLE
Linking Unsuccessful 

### ISSUE THREAD

**Issue by jimmyjampot** [ndg63276/alexa-sky-hd#4]
Just wondering if anyone still supporting this. I’m not too good with the programming side of things but I’ve run through setup and it won’t link

I get 

The authorisation server returned with an error parameter. Please refer to https://tools.ietf.org/html/rfc6749#section-4.1.2.1 for more details.

Any help would be great.

**Comment by ghost** [comment]
I am also getting exactly the same result after going through the instructions twice.

As I am not a programmer, by any means, any help would be appreciated.

**Comment by ghost** [comment]
OK so after reading through the documentation on how to setup authorisation and account linking, I changed the following:
MORE ALEXA SKILL SETUP
Line 7: user_id to profile 

All is working ok.

**Comment by jimmyjampot** [comment]
Lol. Exactly what I did.

**Comment by ndg63276** [comment]
Apologies, only just seen this, not great with github settings. Is this working for you both now? What did you end up putting as the scope?
