### ISSUE TITLE
Pull EPG from Sky

### ISSUE THREAD

**Issue by pingloss** [ndg63276/alexa-sky-hd#5]
Hi,

I've been able to get the app pulling down the channel list info from Sky's site using the following URL:

http://epgservices.sky.com/5.1.1/api/2.1/region/json

and appending it with the region code taken from the list I found here:

https://tvheadend.org/boards/5/topics/11130?page=6

so for example to get the app to pull down the list for my region HTV West HD I set the URL to:

http://epgservices.sky.com/5.1.1/api/2.1/region/json/4101/4/

It seems to be working ok so far.

**Comment by ndg63276** [comment]
Thanks, that's great! I couldn't find that file after it moved last year. I have re-included it in the program. I just use 4101/1 as most channels are the same, obviously you can edit to select your region if you want.

**Comment by jimbo2018** [comment]
What about the sky glass version of the e po g? This has the BBC one regions from 8001 and the English itv regions from 5001.

Kids channels start at 201 not 601. The URL of the JSON ends '/as/services/4101/07/' for North West.

If anyone can help please let me know. The start of the URL is unknown so if someone can help please let me know.

Thanks in advance.
