### ISSUE TITLE
Cannot find SkyQ Box

### ISSUE THREAD

**Issue by AndreaC3p0** [ndg63276/alexa-sky-hd#8]
I read your Readme file and put on works your instruction but after successfully installed my Developer skills, I can't list the sky q box on Alexa.

**Comment by ndg63276** [comment]
Very hard to debug remotely. I suggest you look at the logs. Go to lambda, click on your SkyBox function, click Monitoring, then click "View logs in Cloudwatch". Look at the top log in cloudwatch and see if you can see any errors.

**Comment by AndreaC3p0** [comment]
`I've some records with this error:
START RequestId: 22030ca2-afe2-4685-a4d0-3cbccf9085de Version: $LATEST
Unable to import module 'lambda_function': No module named lambda_function

END RequestId: 22030ca2-afe2-4685-a4d0-3cbccf9085de`

**Comment by ndg63276** [comment]
Well that's the problem. My guess is you've uploaded the wrong zip file.

Download this file https://github.com/ndg63276/alexa-sky-hd/raw/master/Alexa-Skybox.zip

Then upload that zip file to lambda.

**Comment by AndreaC3p0** [comment]
Thanks. Now it's working!
I've a trouble just with the channel names. They are not in sync

**Comment by ndg63276** [comment]
Can you give me an example?

**Comment by AndreaC3p0** [comment]
Yes, I asked some commands in Italian language:
"Alexa, cambia canale a Sky Tg24", digit wrong channel
"Alexa, cambia canale a Italia1", wrong channel.

**Comment by ndg63276** [comment]
Haha! This is an English skill! It won't work for Italian channel names.

**Comment by AndreaC3p0** [comment]
Yes I know, but the problem I think is only the channel names. The command was correctly interpreted. 
It's possible replace a channel list?

**Comment by ndg63276** [comment]
Yes it is possible, there are 2 ways:

1. This is where it finds the UK channels: http://epgservices.sky.com/5.1.1/api/2.1/region/json/4101/1/ - If you can find an Italian version, then I can put that in

2. If you want to make it yourself, you need to make a file like this one: https://github.com/ndg63276/alexa-sky-hd/blob/master/channels-hd.json

**Comment by AndreaC3p0** [comment]
Ok, so I'll make myself a epg list for italian region.
After, how can I use this file? I need to change your code?

**Comment by ndg63276** [comment]
If you make the epg list, I can do the coding.

**Comment by AndreaC3p0** [comment]
Ok ndg63276!
I suggest to introduce a new environment variable to check a location of epg file ;)
[sky-channell-ita.txt](https://github.com/ndg63276/alexa-sky-hd/files/3968264/sky-channell-ita.txt)

**Comment by ndg63276** [comment]
Ok, I've added that file, and some code to use it. You need to re-download https://github.com/ndg63276/alexa-sky-hd/raw/master/Alexa-Skybox.zip, then re-upload it to lambda, then add an Environment Variable with a key of Italia and a value of 1.

**Comment by AndreaC3p0** [comment]
@ndg63276 I checked my list and it works properly in italian! If you want i maked some changes in your code to manage dynamic Channel List. In attach you can find a new version of code, beacuse i'm not able to make a pull request in your repo ;)
[README.txt](https://github.com/ndg63276/alexa-sky-hd/files/3970339/README.txt)
[lambda_function.txt](https://github.com/ndg63276/alexa-sky-hd/files/3970340/lambda_function.txt)

**Comment by ndg63276** [comment]
Glad it works!
