### ISSUE TITLE
port forwarding clarification

### ISSUE THREAD

**Issue by delboydell** [ndg63276/alexa-sky-hd#9]
Hello I wonder if you could help please,
I thought I knew a bit about port forwarding as I have managed to do it for my alarm and slingbox, but its the bit 51111 "to 49160" that I dont understand (or find anything on google) normally the port range is say 10001 to 10001 and that goes to the device with a static IP on your internal network, I have never seen it wrote like that. And if you put 51111 in the 1st field the next number has to be the same not lower?
As I understand it the port 51111 is opened to incoming traffic and it  is sent to the IP address of the device.
Could you please clarify the to 49160 bit please (does it get converted by the router to this port before going to the sky box?
thank you in advance
regards
Phil

**Comment by delboydell** [comment]
EDIT after more digging do you mean port mapping? so the traffic comes in on port 51111 and the router changes this to port 49160 before going to the internal IP of the sky box? 
Dont think the new sky routers have this option, could the traffic not just come on 49160 from the alexa skill with the port details modified there?

**Comment by ndg63276** [comment]
Yeah, sorry, I'm not a network expert. You can just forward port 49160, the only worry would be that someone else might control your Sky box, if they scan IPs with that port open. But that's pretty unlikely.

**Comment by delboydell** [comment]
Great, thanks for clearing that up, I can get on and program the skill.
Thanks for the promt reply.
